Document: findmyhash
Title: Debian findmyhash Manual
Author: <insert document author here>
Abstract: This manual describes what findmyhash is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/findmyhash/findmyhash.sgml.gz

Format: postscript
Files: /usr/share/doc/findmyhash/findmyhash.ps.gz

Format: text
Files: /usr/share/doc/findmyhash/findmyhash.text.gz

Format: HTML
Index: /usr/share/doc/findmyhash/html/index.html
Files: /usr/share/doc/findmyhash/html/*.html
